services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: nestjs_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: nestjs_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - nestjs-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NestJS Application
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3003
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres_password
      - DB_NAME=nestjs_db
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    networks:
      - nestjs-network
    volumes:
      - ./logs:/usr/src/app/logs

networks:
  nestjs-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local